apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  labels:
    app: auth-service
  namespace: default
spec:
  selector:
    app: auth-service
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
      nodePort: 32687
  type: NodePort